/*
 * Copyright (C) 2012  Alejandro Mery <amery@geeks.cl>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define DRIVER_NAME	"pinctrl-sunxi-aw1623"
#define pr_fmt(fmt)	DRIVER_NAME ": " fmt

#include <linux/device.h>
#include <linux/module.h>
#include <linux/pinctrl/pinctrl.h>
#include <linux/platform_device.h>

#include <linux/platform_data/pinctrl-sunxi.h>

static struct pinctrl_pin_desc aw1623_pins[] = {
	PINCTRL_PIN(SUNXI_PA0, "PA0"),
	PINCTRL_PIN(SUNXI_PA1, "PA1"),
	PINCTRL_PIN(SUNXI_PA2, "PA2"),
	PINCTRL_PIN(SUNXI_PA3, "PA3"),
	PINCTRL_PIN(SUNXI_PA4, "PA4"),
	PINCTRL_PIN(SUNXI_PA5, "PA5"),
	PINCTRL_PIN(SUNXI_PA6, "PA6"),
	PINCTRL_PIN(SUNXI_PA7, "PA7"),
	PINCTRL_PIN(SUNXI_PA8, "PA8"),
	PINCTRL_PIN(SUNXI_PA9, "PA9"),
	PINCTRL_PIN(SUNXI_PA10, "PA10"),
	PINCTRL_PIN(SUNXI_PA11, "PA11"),
	PINCTRL_PIN(SUNXI_PA12, "PA12"),
	PINCTRL_PIN(SUNXI_PA13, "PA13"),
	PINCTRL_PIN(SUNXI_PA14, "PA14"),
	PINCTRL_PIN(SUNXI_PA15, "PA15"),
	PINCTRL_PIN(SUNXI_PA16, "PA16"),
	PINCTRL_PIN(SUNXI_PA17, "PA17"),
	PINCTRL_PIN(SUNXI_PB0, "PB0"),
	PINCTRL_PIN(SUNXI_PB1, "PB1"),
	PINCTRL_PIN(SUNXI_PB2, "PB2"),
	PINCTRL_PIN(SUNXI_PB3, "PB3"),
	PINCTRL_PIN(SUNXI_PB4, "PB4"),
	PINCTRL_PIN(SUNXI_PB5, "PB5"),
	PINCTRL_PIN(SUNXI_PB6, "PB6"),
	PINCTRL_PIN(SUNXI_PB7, "PB7"),
	PINCTRL_PIN(SUNXI_PB8, "PB8"),
	PINCTRL_PIN(SUNXI_PB9, "PB9"),
	PINCTRL_PIN(SUNXI_PB10, "PB10"),
	PINCTRL_PIN(SUNXI_PB11, "PB11"),
	PINCTRL_PIN(SUNXI_PB12, "PB12"),
	PINCTRL_PIN(SUNXI_PB13, "PB13"),
	PINCTRL_PIN(SUNXI_PB14, "PB14"),
	PINCTRL_PIN(SUNXI_PB15, "PB15"),
	PINCTRL_PIN(SUNXI_PB16, "PB16"),
	PINCTRL_PIN(SUNXI_PB17, "PB17"),
	PINCTRL_PIN(SUNXI_PB18, "PB18"),
	PINCTRL_PIN(SUNXI_PB19, "PB19"),
	PINCTRL_PIN(SUNXI_PB20, "PB20"),
	PINCTRL_PIN(SUNXI_PB21, "PB21"),
	PINCTRL_PIN(SUNXI_PB22, "PB22"),
	PINCTRL_PIN(SUNXI_PB23, "PB23"),
	PINCTRL_PIN(SUNXI_PC0, "PC0"),
	PINCTRL_PIN(SUNXI_PC1, "PC1"),
	PINCTRL_PIN(SUNXI_PC2, "PC2"),
	PINCTRL_PIN(SUNXI_PC3, "PC3"),
	PINCTRL_PIN(SUNXI_PC4, "PC4"),
	PINCTRL_PIN(SUNXI_PC5, "PC5"),
	PINCTRL_PIN(SUNXI_PC6, "PC6"),
	PINCTRL_PIN(SUNXI_PC7, "PC7"),
	PINCTRL_PIN(SUNXI_PC8, "PC8"),
	PINCTRL_PIN(SUNXI_PC9, "PC9"),
	PINCTRL_PIN(SUNXI_PC10, "PC10"),
	PINCTRL_PIN(SUNXI_PC11, "PC11"),
	PINCTRL_PIN(SUNXI_PC12, "PC12"),
	PINCTRL_PIN(SUNXI_PC13, "PC13"),
	PINCTRL_PIN(SUNXI_PC14, "PC14"),
	PINCTRL_PIN(SUNXI_PC15, "PC15"),
	PINCTRL_PIN(SUNXI_PC16, "PC16"),
	PINCTRL_PIN(SUNXI_PC17, "PC17"),
	PINCTRL_PIN(SUNXI_PC18, "PC18"),
	PINCTRL_PIN(SUNXI_PC19, "PC19"),
	PINCTRL_PIN(SUNXI_PC20, "PC20"),
	PINCTRL_PIN(SUNXI_PC21, "PC21"),
	PINCTRL_PIN(SUNXI_PC22, "PC22"),
	PINCTRL_PIN(SUNXI_PC23, "PC23"),
	PINCTRL_PIN(SUNXI_PC24, "PC24"),
	PINCTRL_PIN(SUNXI_PD0, "PD0"),
	PINCTRL_PIN(SUNXI_PD1, "PD1"),
	PINCTRL_PIN(SUNXI_PD2, "PD2"),
	PINCTRL_PIN(SUNXI_PD3, "PD3"),
	PINCTRL_PIN(SUNXI_PD4, "PD4"),
	PINCTRL_PIN(SUNXI_PD5, "PD5"),
	PINCTRL_PIN(SUNXI_PD6, "PD6"),
	PINCTRL_PIN(SUNXI_PD7, "PD7"),
	PINCTRL_PIN(SUNXI_PD8, "PD8"),
	PINCTRL_PIN(SUNXI_PD9, "PD9"),
	PINCTRL_PIN(SUNXI_PD10, "PD10"),
	PINCTRL_PIN(SUNXI_PD11, "PD11"),
	PINCTRL_PIN(SUNXI_PD12, "PD12"),
	PINCTRL_PIN(SUNXI_PD13, "PD13"),
	PINCTRL_PIN(SUNXI_PD14, "PD14"),
	PINCTRL_PIN(SUNXI_PD15, "PD15"),
	PINCTRL_PIN(SUNXI_PD16, "PD16"),
	PINCTRL_PIN(SUNXI_PD17, "PD17"),
	PINCTRL_PIN(SUNXI_PD18, "PD18"),
	PINCTRL_PIN(SUNXI_PD19, "PD19"),
	PINCTRL_PIN(SUNXI_PD20, "PD20"),
	PINCTRL_PIN(SUNXI_PD21, "PD21"),
	PINCTRL_PIN(SUNXI_PD22, "PD22"),
	PINCTRL_PIN(SUNXI_PD23, "PD23"),
	PINCTRL_PIN(SUNXI_PD24, "PD24"),
	PINCTRL_PIN(SUNXI_PD25, "PD25"),
	PINCTRL_PIN(SUNXI_PD26, "PD26"),
	PINCTRL_PIN(SUNXI_PD27, "PD27"),
	PINCTRL_PIN(SUNXI_PE0, "PE0"),
	PINCTRL_PIN(SUNXI_PE1, "PE1"),
	PINCTRL_PIN(SUNXI_PE2, "PE2"),
	PINCTRL_PIN(SUNXI_PE3, "PE3"),
	PINCTRL_PIN(SUNXI_PE4, "PE4"),
	PINCTRL_PIN(SUNXI_PE5, "PE5"),
	PINCTRL_PIN(SUNXI_PE6, "PE6"),
	PINCTRL_PIN(SUNXI_PE7, "PE7"),
	PINCTRL_PIN(SUNXI_PE8, "PE8"),
	PINCTRL_PIN(SUNXI_PE9, "PE9"),
	PINCTRL_PIN(SUNXI_PE10, "PE10"),
	PINCTRL_PIN(SUNXI_PE11, "PE11"),
	PINCTRL_PIN(SUNXI_PF0, "PF0"),
	PINCTRL_PIN(SUNXI_PF1, "PF1"),
	PINCTRL_PIN(SUNXI_PF2, "PF2"),
	PINCTRL_PIN(SUNXI_PF3, "PF3"),
	PINCTRL_PIN(SUNXI_PF4, "PF4"),
	PINCTRL_PIN(SUNXI_PF5, "PF5"),
	PINCTRL_PIN(SUNXI_PG0, "PG0"),
	PINCTRL_PIN(SUNXI_PG1, "PG1"),
	PINCTRL_PIN(SUNXI_PG2, "PG2"),
	PINCTRL_PIN(SUNXI_PG3, "PG3"),
	PINCTRL_PIN(SUNXI_PG4, "PG4"),
	PINCTRL_PIN(SUNXI_PG5, "PG5"),
	PINCTRL_PIN(SUNXI_PG6, "PG6"),
	PINCTRL_PIN(SUNXI_PG7, "PG7"),
	PINCTRL_PIN(SUNXI_PG8, "PG8"),
	PINCTRL_PIN(SUNXI_PG9, "PG9"),
	PINCTRL_PIN(SUNXI_PG10, "PG10"),
	PINCTRL_PIN(SUNXI_PG11, "PG11"),
	PINCTRL_PIN(SUNXI_PH0, "PH0"),
	PINCTRL_PIN(SUNXI_PH1, "PH1"),
	PINCTRL_PIN(SUNXI_PH2, "PH2"),
	PINCTRL_PIN(SUNXI_PH3, "PH3"),
	PINCTRL_PIN(SUNXI_PH4, "PH4"),
	PINCTRL_PIN(SUNXI_PH5, "PH5"),
	PINCTRL_PIN(SUNXI_PH6, "PH6"),
	PINCTRL_PIN(SUNXI_PH7, "PH7"),
	PINCTRL_PIN(SUNXI_PH8, "PH8"),
	PINCTRL_PIN(SUNXI_PH9, "PH9"),
	PINCTRL_PIN(SUNXI_PH10, "PH10"),
	PINCTRL_PIN(SUNXI_PH11, "PH11"),
	PINCTRL_PIN(SUNXI_PH12, "PH12"),
	PINCTRL_PIN(SUNXI_PH13, "PH13"),
	PINCTRL_PIN(SUNXI_PH14, "PH14"),
	PINCTRL_PIN(SUNXI_PH15, "PH15"),
	PINCTRL_PIN(SUNXI_PH16, "PH16"),
	PINCTRL_PIN(SUNXI_PH17, "PH17"),
	PINCTRL_PIN(SUNXI_PH18, "PH18"),
	PINCTRL_PIN(SUNXI_PH19, "PH19"),
	PINCTRL_PIN(SUNXI_PH20, "PH20"),
	PINCTRL_PIN(SUNXI_PH21, "PH21"),
	PINCTRL_PIN(SUNXI_PH22, "PH22"),
	PINCTRL_PIN(SUNXI_PH23, "PH23"),
	PINCTRL_PIN(SUNXI_PH24, "PH24"),
	PINCTRL_PIN(SUNXI_PH25, "PH25"),
	PINCTRL_PIN(SUNXI_PH26, "PH26"),
	PINCTRL_PIN(SUNXI_PH27, "PH27"),
	PINCTRL_PIN(SUNXI_PI0, "PI0"),
	PINCTRL_PIN(SUNXI_PI1, "PI1"),
	PINCTRL_PIN(SUNXI_PI2, "PI2"),
	PINCTRL_PIN(SUNXI_PI3, "PI3"),
	PINCTRL_PIN(SUNXI_PI4, "PI4"),
	PINCTRL_PIN(SUNXI_PI5, "PI5"),
	PINCTRL_PIN(SUNXI_PI6, "PI6"),
	PINCTRL_PIN(SUNXI_PI7, "PI7"),
	PINCTRL_PIN(SUNXI_PI8, "PI8"),
	PINCTRL_PIN(SUNXI_PI9, "PI9"),
	PINCTRL_PIN(SUNXI_PI10, "PI10"),
	PINCTRL_PIN(SUNXI_PI11, "PI11"),
	PINCTRL_PIN(SUNXI_PI12, "PI12"),
	PINCTRL_PIN(SUNXI_PI13, "PI13"),
	PINCTRL_PIN(SUNXI_PI14, "PI14"),
	PINCTRL_PIN(SUNXI_PI15, "PI15"),
	PINCTRL_PIN(SUNXI_PI16, "PI16"),
	PINCTRL_PIN(SUNXI_PI17, "PI17"),
	PINCTRL_PIN(SUNXI_PI18, "PI18"),
	PINCTRL_PIN(SUNXI_PI19, "PI19"),
	PINCTRL_PIN(SUNXI_PI20, "PI20"),
	PINCTRL_PIN(SUNXI_PI21, "PI21"),
};

static struct sunxi_pinctrl_soc_data aw1623_pinctrl = {
	.name = "aw1623",
	.pins = aw1623_pins,
	.npins = ARRAY_SIZE(aw1623_pins),
};

static int __devinit aw1623_pinctrl_probe(struct platform_device *pdev)
{
	return sunxi_pinctrl_probe(pdev, &aw1623_pinctrl);
}

static struct of_device_id aw1623_pinctrl_of_match[] __devinitdata = {
	{ .compatible = "allwinner,aw1623-pinctrl", },
	{ .compatible = "allwinner,sunxi-aw1623-pinctrl", },
	{ .compatible = "allwinner,sunxi-a10-pinctrl", },
	{ },
};

static struct platform_driver aw1623_pinctrl_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table = aw1623_pinctrl_of_match,
	},
	.probe = aw1623_pinctrl_probe,
	.remove = __devexit_p(sunxi_pinctrl_remove),
};

static int __init aw1623_pinctrl_init(void)
{
	return platform_driver_register(&aw1623_pinctrl_driver);
}
arch_initcall(aw1623_pinctrl_init);

static void __exit aw1623_pinctrl_exit(void)
{
	platform_driver_unregister(&aw1623_pinctrl_driver);
}
module_exit(aw1623_pinctrl_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Alejandro Mery <amery@geeks.cl>");
MODULE_DESCRIPTION("sunxi (A10/AW1623) pin control driver");
MODULE_DEVICE_TABLE(of, aw1623_pinctrl_of_match);
